#!/usr/bin/env python# -*- coding: utf-8 -*-

from __future__ import division
import math
import numpy as np
import scipy as sp
import pandas
import matplotlib.pyplot as plt
from progressbar import ProgressBar
from scipy.sparse import csr_matrix
from scipy.sparse import linalg as sparse_linalg
import sys
file_dir = '/localhome/pykb/physics_code/Exact_Diagonalization/Classes/'
sys.path.append(file_dir)
file_dir = '/localhome/pykb/physics_code/Exact_Diagonalization/functions/'
sys.path.append(file_dir)

from Hamiltonian_Classes import Hamiltonian,H_table,clock_Hamiltonian,spin_Hamiltonian
from System_Classes import unlocking_System
from Symmetry_Classes import translational,parity,model_sym_data,charge_conjugation
# from Plotting_Classes import eig_overlap,fidelity,entropy,energy_basis
from Non_observables import zm
from Construction_functions import bin_to_int_base_m,int_to_bin_base_m,cycle_bits_state
from Search_functions import find_index_bisection
from State_Classes import zm_state,sym_state,prod_state,bin_state,ref_state
from rw_functions import save_obj,load_obj
from Calculations import level_stats,fidelity,eig_overlap,entropy,site_precession,site_projection,time_evolve_state

from matplotlib import rc
rc('font',**{'family':'sans-serif','sans-serif':['Computer Modern'],'size':26})
## for Palatino and other serif fonts use:
#rc('font',**{'family':'serif','serif':['Palatino']})
rc('text', usetex=True)
# matplotlib.rcParams['figure.dpi'] = 400

def find_hamming_sectors(state_bits,system):
    #organize states via hamming distance from Neel
    hamming_sectors = dict()
    for n in range(0,system.N+1):
        hamming_sectors[n] = []
    for n in range(0,system.dim):
        h = 0
        for m in range(0,system.N,1):
            if system.basis[n][m] != state_bits[m]:
                h = h+1
        hamming_sectors[int(h)] = np.append(hamming_sectors[int(h)],system.basis_refs[n])
    return hamming_sectors

#returns krylov basis, n vectors generated by n applications of H on v
def krylov(v,H,krylov_size):
    #generate subspace by repeated application of H
    temp = v
    for n in range(0,krylov_size):
        temp = np.dot(H,temp)
        v = np.vstack((v,temp))

    #orthonormalize basis using QR decomposition
    v = np.transpose(v)
    #orthornormalize with qr decomp
    x,r = np.linalg.qr(v)
    return x

#init small hypercube
N=8
pxp = unlocking_System([0],"periodic",2,N)
pxp.gen_basis()
pxp_syms = model_sym_data(pxp,[translational(pxp)])

z=zm_state(2,1,pxp)
H=spin_Hamiltonian(pxp,"x")
H.gen()
H.sector.find_eig()

#form krylov subspace
krylov_dim = pxp.N+4
krylov_basis = krylov(z.prod_basis(),H.sector.matrix(),krylov_dim)

perm_labels = np.zeros((pxp.dim,2))
for n in range(0,np.size(pxp.basis_refs,axis=0)):
    c1 = 0
    c2 = 0
    for m in range(0,pxp.N-1,2):
        if  pxp.basis[n][m] == 1:
            c1 = c1 + 1
        if pxp.basis[n][m+1] == 1:
            c2 = c2 + 1
    perm_labels[n] = np.array((c1,c2))
    
from Diagnostics import print_wf
for n in range(0,np.size(krylov_basis,axis=1)):
    print("\n")
    for m in range(0,np.size(krylov_basis[:,n],axis=0)):
        if np.abs(krylov_basis[m,n])>1e-5:
            print(np.abs(krylov_basis[m,n]),pxp.basis[m],perm_labels[m])
    
H_rot = np.dot(np.conj(np.transpose(krylov_basis)),np.dot(H.sector.matrix(),krylov_basis))
plt.matshow(np.abs(H_rot))
plt.show()

exact_overlap = eig_overlap(z,H).eval()
plt.scatter(H.sector.eigvalues(),exact_overlap,label="Exact")

e,u = np.linalg.eigh(H_rot)
psi_energy = np.conj(u[0,:])
overlap = np.log10(np.abs(psi_energy)**2)
plt.scatter(e,overlap,marker="x",s=100,color="red",label="krylov")

plt.legend()
plt.show()

u_comp_basis = np.dot(krylov_basis,u)
m_overlaps = np.zeros(np.size(e))
for n in range(0,np.size(u_comp_basis,axis=1)):
    max_overlap = 0
    for m in range(0,np.size(H.sector.eigvalues(),axis=0)):
        temp = np.abs(np.vdot(u_comp_basis[:,n],H.sector.eigvectors()[:,m]))**2
        if temp > max_overlap:
            max_overlap = temp
    m_overlaps[n] = max_overlap
plt.scatter(e,m_overlaps)
plt.show()
print(m_overlaps)
